apiVersion: v1
kind: Pod
metadata:
  name: minifeed
  labels:
    app: minifeed
spec:
  containers:
  - name: minifeed
    image: saiteja13/mini-feed-writer-react:v1
    ports:
      - containerPort: 3000
        name: minifeed