apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  #type: ClusterIP  #this is default so commenting out
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
      name: "db-service"