apiVersion: v1
kind: Pod
metadata:
  name: post-api
  labels:
    app: post-api
spec:
  containers:
  - name: post-api
    image: saiteja13/mini-feed-post-api:v1
    env:
      - name: REDIS_URL
        value: "redis://redis:6379"
    ports:
      - containerPort: 4000
